#plugins used
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-redirect-from]

# Site settings
title: ICT Solved!
description: > # this means to ignore newlines until "baseurl:"
  ICT Solved! is a tech blog created with an aim to update readers with the posts related with computer, programming and technology. ICT Solved! covers wide variety of posts with useful tips and tricks.
baseurl: ""
url: "https://ictsolved.com"

# Build settings
markdown: kramdown
permalink: /:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post is

# Pagination
paginate: 5
paginate_path: /page/:num
defaults:
  - scope:
      path: "page"
    values:
      sitemap: false
      robots: noindex

## default date_format
date_format:
  archive: "%b %d"
  post: "%b %-d, %Y"
