### GENERAL SETTINGS ###

#gems used
gems:
   - jekyll-seo-tag
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-feed
   - jekyll-sitemap

# Site settings
title: ICT Solved!
description: "A complete web portal to solve your problems related with Android, iOS, Linux and Windows."
#baseurl: ""
url: "https://ictsolved.github.io"
blog_img_path: "/assets/img/blog/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
      - title: facebook
        url: https://facebook.com/daju.sarad
      - title: twitter
        url: https://twitter.com/Sarad_Gajurel
      - title: github
        url: https://github.com/ictsolved
      - title: linkedin
        url: https://np.linkedin.com/in/sarad-gajurel-10a236120
      - title: google-plus
        url: https://plus.google.com/u/0/105332295114267466679
      - title: pinterest-p
        url: https://www.pinterest.com/saradgajurel
      - title: reddit-alien
        url: https://www.reddit.com/user/saradgajurel
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Suryakot,
    - Koteshwor, 34,
    - Bagmati, Nepal


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Sarad Gajurel
    position: Author
    text: I am a Computer Science student and author at ICT Solved!. Along with my studies, I am partly working as a cloud worker. Updating myself with ICT, experimenting with computers and codes, ethical hacking, blogging, content writing, sharing my knowledge and experience with other, and singing are my hobbies.
    img: sarad.png
    social:
      - title: facebook
        url: https://facebook.com/daju.sarad
      - title: twitter
        url: https://twitter.com/Sarad_Gajurel
      - title: github
        url: https://github.com/ictsolved
      - title: linkedin
        url: https://np.linkedin.com/in/sarad-gajurel-10a236120
      - title: google-plus
        url: https://plus.google.com/u/0/105332295114267466679
      - title: pinterest-p
        url: https://www.pinterest.com/saradgajurel
      - title: reddit-alien
        url: https://www.reddit.com/user/saradgajurel
    
# Clients information. Shown on Home and About pages.
used:
  - name: Bootstrap
    img: bootstrap.png
  - name: CSS3
    img: CSS3.png
  - name: HTML5
    img: HTML5.png
  - name: Jekyll
    img: jekyll.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "ICT Solved! is created by Sarad Gajurel with an aim to solve your problems that arise in Linux, Windows, Android and iOS. Your feedbacks are welcomed."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "I am a student studying BSc. CSIT with a great enthusiasm and effort to become a successful IT professional. I want to contribute something valuable to my community, society, country and possibly to the whole world in the sector of ICT. ICT is a such field where revolution can be brought in moment of time and to bring that revolution the evolution of the ideas are needed. Trend being used should be revised in a manner that has not been implemented yet! I am on the way to it."
    author: Sarad Gajurel
    position: Author
